CURR_DIR=`dirname $0`

source $CURR_DIR/zgen/zgen.zsh

source $CURR_DIR/alias.zsh
source $CURR_DIR/history.zsh
source $CURR_DIR/directory.zsh
source $CURR_DIR/completion.zsh
source $CURR_DIR/key_info.zsh

if ! zgen saved; then
  echo "Creating zgen save"

  zgen oh-my-zsh
  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/command-not-found
  zgen oh-my-zsh plugins/autojump
  zgen oh-my-zsh plugins/tmux
  zgen oh-my-zsh plugins/rake-fast
  zgen oh-my-zsh plugins/gitfast
  zgen oh-my-zsh plugins/colored-man-pages

  zgen load zsh-users/zsh-completions src
  zgen load zsh-users/zsh-syntax-highlighting
  zgen load zsh-users/zsh-history-substring-search
  zgen load djui/alias-tips

  zgen oh-my-zsh themes/frisk

  if [ -f ~/.zgen.local ]; then
    source .zgen.local
  fi

  zgen save
fi

#
# Key Bindings For history-substring-search
#

if [[ -n "$key_info" ]]; then
  # Emacs
  bindkey -M emacs "$key_info[Control]P" history-substring-search-up
  bindkey -M emacs "$key_info[Control]N" history-substring-search-down

  # Vi
  bindkey -M vicmd "k" history-substring-search-up
  bindkey -M vicmd "j" history-substring-search-down

  # Emacs and Vi
  for keymap in 'emacs' 'viins'; do
    bindkey -M "$keymap" "$key_info[Up]" history-substring-search-up
    bindkey -M "$keymap" "$key_info[Down]" history-substring-search-down
  done
fi

# set $TERM correctly {{{
if [ -z "$TMUX" ] ; then
  if [ -n "$COLORTERM" ] ; then
    if [ "$COLORTERM" = "xfce4-terminal" ] ; then
      export TERM=xterm-256color
    fi
  fi
fi
# }}}

# set other var
export  EDITOR=vim

if [ -f ~/.zshrc.local ]; then
  source .zshrc.local
fi
