CURR_DIR=`dirname $0`
source $CURR_DIR/zgen/zgen.zsh

source $CURR_DIR/alias.zsh
source $CURR_DIR/history.zsh
source $CURR_DIR/directory.zsh
source $CURR_DIR/completion.zsh

if ! zgen saved; then
  echo "Creating zgen save"

  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/command-not-found
  zgen load zsh-users/zsh-history-substring-search
  zgen load zsh-users/zsh-completions src

  zgen load mafredri/zsh-async
  zgen load sindresorhus/pure

  zgen save
fi

# set $TERM correctly {{{
if [ -z "$TMUX" ] ; then
  if [ -n "$COLORTERM" ] ; then
    if [ "$COLORTERM" = "xfce4-terminal" ] ; then
      export TERM=xterm-256color
    fi
  fi
fi
# }}}
